### PR TITLE
Add function to pass string to WASM

### PR DESCRIPTION
**Pull request by duckymirror**
This PR adds a helper function that passes a string to the WASM instance. The string has to be deallocated by the WASM code.

### CODE REVIEW

**Comment by L0laapk3** [comment]
cool but what is the use case of this?

**Comment by duckymirror** [comment]
It can be used for reading a spirit's `mark`.

**Comment by L0laapk3** [comment]
Why do you need this? I deliberately left mark out of the API. If you need to store things about spirits, the way I recommend is by storing a global `map` with as key `Spirit.id`, or `{ Spirit.playerId, Spirit.id }` if you want to mix friendly and enemy spirits. Would this suit your needs?

Aside from that, I'll keep this in the back of my mind in the future if some update does make string JS to WASM useful. That minified file, whats the source? Does it come with a license?

**Comment by duckymirror** [comment]
The file is from this repo: https://github.com/anonyco/FastestSmallestTextEncoderDecoder
It's licensed under CC0.

The reason why I wanted to add `mark` and `set_mark` is only for the sake of completeness. But it's reasonable to leave it out to encourage WASM-only solutions, which have better performance anyway.

**Pull request closed without merging**
